embeddings {
tensor_name: "embedding/sample:00000"
tensor_path: "00000/embedding%2fsample/tensors.tsv"
metadata_path: "00000/embedding%2fsample/metadata.tsv"
sprite {
image_path: "00000/embedding%2fsample/sprite.png"
single_image_dim: 8
single_image_dim: 8
}
}
