# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: tensorboard/plugins/custom_scalar/layout.proto
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n.tensorboard/plugins/custom_scalar/layout.proto\x12\x0btensorboard"\x8d\x01\n\x05Chart\x12\r\n\x05title\x18\x01 \x01(\t\x127\n\tmultiline\x18\x02 \x01(\x0b2".tensorboard.MultilineChartContentH\x00\x121\n\x06margin\x18\x03 \x01(\x0b2\x1f.tensorboard.MarginChartContentH\x00B\t\n\x07content"$\n\x15MultilineChartContent\x12\x0b\n\x03tag\x18\x01 \x03(\t"\x83\x01\n\x12MarginChartContent\x126\n\x06series\x18\x01 \x03(\x0b2&.tensorboard.MarginChartContent.Series\x1a5\n\x06Series\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05lower\x18\x02 \x01(\t\x12\r\n\x05upper\x18\x03 \x01(\t"L\n\x08Category\x12\r\n\x05title\x18\x01 \x01(\t\x12!\n\x05chart\x18\x02 \x03(\x0b2\x12.tensorboard.Chart\x12\x0e\n\x06closed\x18\x03 \x01(\x08"B\n\x06Layout\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\'\n\x08category\x18\x02 \x03(\x0b2\x15.tensorboard.Categoryb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tboardfs.proto.custom_scalar_layout_pb2", globals()
)
