# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: tensorboard/plugins/hparams/plugin_data.proto
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder

from tboardfs.proto import hparams_api_pb2 as _hparams_api_pb2


_HPARAMS_API_DESCRIPTOR = _hparams_api_pb2.DESCRIPTOR

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n-tensorboard/plugins/hparams/plugin_data.proto\x12\x13tensorboard.hparams\x1a%tensorboard/plugins/hparams/api.proto\x1a\x1cgoogle/protobuf/struct.proto"\xe9\x01\n\x11HParamsPluginData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x125\n\nexperiment\x18\x02 \x01(\x0b2\x1f.tensorboard.hparams.ExperimentH\x00\x12C\n\x12session_start_info\x18\x03 \x01(\x0b2%.tensorboard.hparams.SessionStartInfoH\x00\x12?\n\x10session_end_info\x18\x04 \x01(\x0b2#.tensorboard.hparams.SessionEndInfoH\x00B\x06\n\x04data"\xf4\x01\n\x10SessionStartInfo\x12C\n\x07hparams\x18\x01 \x03(\x0b22.tensorboard.hparams.SessionStartInfo.HparamsEntry\x12\x11\n\tmodel_uri\x18\x02 \x01(\t\x12\x13\n\x0bmonitor_url\x18\x03 \x01(\t\x12\x12\n\ngroup_name\x18\x04 \x01(\t\x12\x17\n\x0fstart_time_secs\x18\x05 \x01(\x01\x1aF\n\x0cHparamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b2\x16.google.protobuf.Value:\x028\x01"T\n\x0eSessionEndInfo\x12+\n\x06status\x18\x01 \x01(\x0e2\x1b.tensorboard.hparams.Status\x12\x15\n\rend_time_secs\x18\x02 \x01(\x01b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tboardfs.proto.hparams_plugin_data_pb2", globals()
)
