# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: tensorboard/plugins/hparams/api.proto
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import builder as _builder


_STRUCT_DESCRIPTOR = _struct_pb2.DESCRIPTOR

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%tensorboard/plugins/hparams/api.proto\x12\x13tensorboard.hparams\x1a\x1cgoogle/protobuf/struct.proto"\xc6\x01\n\nExperiment\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x13\n\x0bdescription\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x19\n\x11time_created_secs\x18\x03 \x01(\x01\x125\n\x0chparam_infos\x18\x04 \x03(\x0b2\x1f.tensorboard.hparams.HParamInfo\x125\n\x0cmetric_infos\x18\x05 \x03(\x0b2\x1f.tensorboard.hparams.MetricInfo"\xfe\x01\n\nHParamInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12\x13\n\x0bdescription\x18\x03 \x01(\t\x12+\n\x04type\x18\x04 \x01(\x0e2\x1d.tensorboard.hparams.DataType\x125\n\x0fdomain_discrete\x18\x05 \x01(\x0b2\x1a.google.protobuf.ListValueH\x00\x128\n\x0fdomain_interval\x18\x06 \x01(\x0b2\x1d.tensorboard.hparams.IntervalH\x00\x12\x0f\n\x07differs\x18\x07 \x01(\x08B\x08\n\x06domain"0\n\x08Interval\x12\x11\n\tmin_value\x18\x01 \x01(\x01\x12\x11\n\tmax_value\x18\x02 \x01(\x01"(\n\nMetricName\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t"\x9e\x01\n\nMetricInfo\x12-\n\x04name\x18\x01 \x01(\x0b2\x1f.tensorboard.hparams.MetricName\x12\x14\n\x0cdisplay_name\x18\x03 \x01(\t\x12\x13\n\x0bdescription\x18\x04 \x01(\t\x126\n\x0cdataset_type\x18\x05 \x01(\x0e2 .tensorboard.hparams.DatasetType*`\n\x08DataType\x12\x13\n\x0fDATA_TYPE_UNSET\x10\x00\x12\x14\n\x10DATA_TYPE_STRING\x10\x01\x12\x12\n\x0eDATA_TYPE_BOOL\x10\x02\x12\x15\n\x11DATA_TYPE_FLOAT64\x10\x03*P\n\x0bDatasetType\x12\x13\n\x0fDATASET_UNKNOWN\x10\x00\x12\x14\n\x10DATASET_TRAINING\x10\x01\x12\x16\n\x12DATASET_VALIDATION\x10\x02*X\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_FAILURE\x10\x02\x12\x12\n\x0eSTATUS_RUNNING\x10\x03b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tboardfs.proto.hparams_api_pb2", globals()
)
